### ISSUE TITLE
Substitutions being resolved in reference.conf before merge with application.conf

### ISSUE THREAD

**Issue by ruippeixotog** [typesafehub/config#214]
I have a system where I have `reference.conf` and `application.conf` files more or less like this:

```
# reference.conf
main-service {
  host = "127.0.0.1"
  port = 9000
}

other-service {
  host = ${main-service.host}
  port = 9001
}
```

```
# application.conf
main-service.host = "myservice.com"
```

In this situation, I was expecting the value of `other-service.host` to be resolved to "myservice.com", as it would happen if I specified everything in a single file (or in multiple files included by another). I looked up in the source code and found that the defaultReference is being [resolved before returned](https://github.com/typesafehub/config/blob/f3ec3aa9108df03e1cf147c6775fb5e0cb06e2cf/config/src/main/java/com/typesafe/config/impl/ConfigImpl.java#L373). Is there any special reason for this? In my case, it would be a lot handier if everything was resolved only [on load time](https://github.com/typesafehub/config/blob/f3ec3aa9108df03e1cf147c6775fb5e0cb06e2cf/config/src/main/java/com/typesafe/config/ConfigFactory.java#L202).

**Comment by munkyboy** [comment]
this is hokey but seems to work:

`reference.conf`

    main-service {
      host = "127.0.0.1"
      port = 9000
    }
    
    include "application"

    other-service {
      host = ${main-service.host}
      port = 9001
    }

`application.conf`

    main-service.host = "myservice.com"

**Comment by havocp** [comment]
Please don't include application.conf in reference.conf in a general-consumption public library, it's likely to cause all kinds of trouble. It makes app-specific config (that maybe isn't even supposed to be used due to -Dconfig.file or a custom setup) part of the default reference config.

Much better would be to set other-service.host to empty string or null in reference.conf and then include an application.conf also in your jar that sets other-service.host = ${main-service.host}. That way people who are actually using application.conf get the setting but you aren't forcing use of application.conf.
