### ISSUE TITLE
AST API? (was: Obtaining unresolved values: is it possible?)

### ISSUE THREAD

**Issue by paulp** [typesafehub/config#225]
I'm out of ideas. The relevant-sounding setAllowUnresolved in ConfigResolveOptions seems not to be so relevant. (It also has a confusing typo in the javadoc - presumably "will now throw" is supposed to be "will NOT throw".) 

Here's what I came up with which works. Is there some way to accomplish this without injecting classes into the com.typesafe.config.impl package?
```scala
import com.typesafe.config._

package com.typesafe.config.impl {
  object directGet {
    def apply(c: Config, key: String) = (
      Some(c.root)
        collect { case x: SimpleConfigObject => x attemptPeekWithPartialResolve key }
        collect { case x: ConfigReference => x.expression.path.render }
        getOrElse ""
    )
  }
}
package object app {
  implicit class ConfigOps(val c: Config) {
    def directGet(key: String) = com.typesafe.config.impl.directGet(c, key)
  }

  def demo(): String = {
    val c = ConfigFactory parseString "a: { b: c }, z: ${a}"
    c directGet "z"
  }
}
// Desired outcome:
// scala> app.demo
// res0: String = a
```

**Comment by havocp** [comment]
I think you could avoid attemptPeekWithPartialResolve by catching an exception instead (look at ConfigException subtypes for the relevant one). There is no public API for references though. If you tell me the bigger picture goal of getting this then there could be another solution, possibly.

I think the now/not typo may be fixed already in master.

**Comment by havocp** [comment]
https://github.com/typesafehub/config/blob/master/config/src/main/java/com/typesafe/config/ConfigException.java#L296 is the exception but it's currently documented as an assertion failure, essentially.

**Comment by paulp** [comment]
I would be more than willing to catch an exception, but it doesn't get me any closer to the unresolved value which corresponds to the key unless I parse it out of the exception string, at which point I could just parse it out of the original Config's string representation since it isn't being hidden.
```scala
scala> val c = ConfigFactory parseString "a: { b: c }, z: ${a}"
c: Config = Config(SimpleConfigObject({"a":{"b":"c"},"z":${a}})) // <-- see
```
The bigger picture is the analog to being able to parse scala code without it insisting on performing a bunch of desugaring. I'm modeling the configuration file, and an unresolved reference should be modeled as a "symbolic link" to the thing which it references, not as a "hard link" where one cannot determine what was actually written in the configuration.

**Comment by havocp** [comment]
As you can tell there's no attempt to provide a "HOCON AST" API at the moment - only the "cooked" Config which is either considered "not usable yet" when unresolved, or "JSON-equivalent losing all HOCON stuff" when resolved. In both cases original formatting is lost.

Depending on what you are doing, #178 could be related (about preserving all the original file formatting).

Another complexity you would encounter here is that you can have a ConfigDelayedMerge in addition to a ConfigReference when things aren't resolved. A ConfigDelayedMerge is a stack of things including at least one ConfigReference, which will be merged once the reference is resolved.

There are also "undelayed" merges which will simply vanish by the time you see them; this happens if you set a field to two different (non-substitution) values, all but the last will just be dropped.

My first idea for how to support some of this would be a separate AST kind of API. It could potentially avoid the merge problem by not supporting merge at the AST level, instead fields would always have the potential for N values. It could also keep all the formatting information hanging around. It could also lack support for all the type conversions (getters wouldn't do any converting of values) and lack support for resolving. It would be a much more "raw textual" API in short without trying to interpret anything.

This is a lot of work though. A simple pragmatic solution might be to poke in library internals and just cope if the impl ABI changes.  But I don't know your goals and constraints.

**Comment by havocp** [comment]
If you mess with the code at all be aware that there's a large PR open to redo how resolution works that touches ConfigDelayedMerge and ConfigReference and friends. I am planning to land that and fix a batch of small things and do a 1.3 release, probably in February or so.

**Comment by paulp** [comment]
Not too bad. Green is a string key, red is a path expression, cyan is a config value. This is a rendering of the AST I wrote for hocon-as-it-is-written.

![ast](https://cloud.githubusercontent.com/assets/9135/5593184/e7bad14a-91b0-11e4-93eb-561ddf648a39.png)

**Comment by havocp** [comment]
The bulk of the hard stuff is now done here thanks to @fpringvaldsen ; two remaining pieces are more specifically described as #299 and #300. At this point I'm not sure those remaining bits will be in 1.3.0, but they aren't a ton of work so I imagine they will get done at some point. I'll close this issue since #299 and #300 are more specific and less cluttered places to discuss what's left.
