### ISSUE TITLE
Reading config properties in order they appear in file

### ISSUE THREAD

**Issue by alexmacavei** [typesafehub/config#235]
Hello, 

First of all I want to thank the contributors for this great tool.
My question is this: If I have an application.conf file in which I list the following properties:
```properties
result {
  property1=1,
  property2=2,
  property3=3
}
```
Now I need to get a map (Scala) of these items in this exact order, but when I do:
```scala
val cfg = ConfigFactory.load
cfg.getConfig("result").entrySet().asScala.foreach(println)
```
it seems that the properties are loaded (hashed?) randomly. Namely, instead of getting a map containing ("property1", ConfigInt(1)), ("property2", ConfigInt(2), ("property3",ConfigInt(3)) I get them mixed.

Could anyone help me out with an advice, I've googled for 1 day and a half already :-(

Thanks very much,
Alex

**Comment by havocp** [comment]
This was discussed a bit in #35, and to me it seemed intractable. Meaningful order doesn't play well with the way the library works in general. Note that even if Config was ordered, your call to entrySet there would trash the order (because Set isn't ordered either). I think if you need order the best solution at the moment is to use the list syntax, as you would in JavaScript or JSON to get ordering. Though if someone wants to grapple with the issues in #35 and come up with some new ideas they are welcome. The one case where order does matter in the config syntax is in constructing merges, so `a = [], a += 1, a += 2` should always give you `a = [1,2]` and not `a = [2,1]`. This may be a useful property depending on what you're doing.

**Comment by alexmacavei** [comment]
Thanks for your response!

Here's how I did it:
As you said, I defined my result as a list in the properties file (application.conf). 
```properties
result = [
  {key: "property1", value: 1},
  {key: "property2", value: 2},
  {key: "property3", value: 3}
]
```
Afterwards, I used a list of tuples instead of map, as the ordering was a priority:
```scala
val cfg = ConfigFactory.load
cfg.getConfigList("result").asScala.toList.map(x => x.getString("key") -> x.getInt("value"))
```

Thanks again, hope this helps somebody.

Alex

**Comment by havocp** [comment]
Thanks, glad you found a solution.
