### ISSUE TITLE
Be specific about which reference.conf had a read error

### ISSUE THREAD

**Issue by jroper** [typesafehub/config#254]
As [this](https://groups.google.com/forum/#!topic/play-framework/SxA7b8jYtOI) mailing list post shows, saying there was a read error in `reference.conf` is not very helpful, because there are many `reference.conf`'s on the classpath, and if one of them comes from a corrupted jar file, but the error message doesn't say which one, then there's no simple way forward to solving the problem.

**Comment by havocp** [comment]
`-Dconfig.trace=loads` should have shown the problem URL, if you want to point people there next time.

It looks like the bug here is that `elementOrigin` here: https://github.com/typesafehub/config/blob/master/config/src/main/java/com/typesafe/config/impl/Parseable.java#L602 
is not known to the caller, so the origin in ConfigException.IO is reference.conf instead of a specific URL, here: https://github.com/typesafehub/config/blob/master/config/src/main/java/com/typesafe/config/impl/Parseable.java#L183 .

I believe once `ConfigException.IO` has the proper origin it will include it in the message.

The fix requires some code rearrangement because the open/read/close of the Reader needs to be covered by a try/catch that has the right origin, and the obvious thing (make a version of parseValue that takes a reader) doesn't work because the open/close of the reader wouldn't get the right origin. A possible fix is to create `ParseableResource` which would take the resource URL and be like `ParseableURL` except with the right `relativeTo` implementation.

**Comment by jroper** [comment]
Thanks @havocp.
