### ISSUE TITLE
Handle dotted properties keys correctly

### ISSUE THREAD

**Issue by TheBoegl** [typesafehub/config#297]
If you parse a properties file using the FileFactory.parse(URL) method dotted keys may be handled incorrectly.
Parsing the following properties example looses the first `log=Log` assignment.
```properties
log=Log
log.folder=Log folder
log.file=Log file
```
This issue is due to the parsing of `log` to a map key, which only references the `folder` and `file` values.
The expected result would be `"Log".equals(config.getString("log"))`.

**Comment by havocp** [comment]
This is unfortunately not fixable. https://github.com/typesafehub/config/blob/master/HOCON.md#java-properties-mapping describes the problem. We use the JSON data model which does not have string values associated with each object in an object tree, so we can't represent that. Also the Java properties file parser doesn't give us a defined order, so we can't make it order-dependent. So we always prefer to create the `log` object, rather than the `log` string value, in a case like this. We could have arbitrarily preferred the opposite (keep the string value), but in any case it would be an ABI break to change that now.

You have to use the Java properties parser directly to get at this, in short - there's no way to tunnel it through the `Config` interface.

**Comment by havocp** [comment]
Is this in a .properties file? The hocon spec wouldn’t apply to a file in Java properties format

**Comment by jhansche** [comment]
The discussion is relevant in the context of a hocon conf file (specifically, I'm working with [gradle-profiler](https://github.com/gradle/gradle-profiler), which uses the hocon format for its scenarios file).  In my example (which is the same issue that OP is having):

```
scenario1 {
    system-properties {
        org.gradle.parallel = true
        org.gradle.caching = true
        org.gradle.project.android.enableD8 = false
        org.gradle.project.android.enableR8 = false
        org.gradle.project.android.enableD8.desugaring = true
    }
}
```

All other properties work, but when setting the `android.enableD8=true` and `android.enableD8.desugaring=true` properties, the `android.enableD8` property is lost due to this issue.

I tried working around it by setting them with:
```
        org.gradle.project."android.enableD8" = false
        org.gradle.project."android.enableD8.desugaring" = true
        // or:
        "org.gradle.project.android.enableD8.desugaring" = true
```

and rather than treat the quoted parts of the key as literal string key names (i.e., bypassing the dotted object path behavior as documented), it is instead explicitly adding the `"` to the property names, which is not what I expected based on the lines of the documentation that I quoted above.

**Comment by havocp** [comment]
The original issue here is about a .properties file, but if your file is named .conf the issue would be different.

 Can you add a failing test to the test suite maybe, or provide a failing test program? If json-style quoting were broken in .conf files I’d expect a LOT of people to report it, so there’s likely something more situational involved here.

**Comment by jhansche** [comment]
OK, I see now OP was talking about a properties file; but the symptom appears to be the same:  wanting a way to opt out of the dotted object expansion in such a way as to have a field key name that itself contains dots, even if one of those keys looks like it would try to convert an existing key's scalar value into an object.

I'll see if I can reproduce my issue in a test case. It's also possible this is an issue with the way the gradle-profiler parses the file, so I'll check that too.

**Comment by havocp** [comment]
:+1: thanks for digging in on it and figuring it out!
