### ISSUE TITLE
Is possible to use typesafe config in SBT to config build itself ?

### ISSUE THREAD

**Issue by chesterxgchen** [typesafehub/config#319]
I have used the typesafe config at runtime and the dependency specified in SBT. 

But while I configure the build itself in SBT Build.scala, I have to use java properties to control the build. Is it possible to use ConfigFactory (and application.conf) to configure the build itself, so I have only one configuration to manage ?

**Comment by havocp** [comment]
It's best to ask questions like this on stackoverflow where many people will see them. Here it's just one or two maintainers.

Short answer you can use any library you want from sbt (add to libraryDependencies of the build, in project/foo.sbt, rather than foo.sbt in the root directory). But sbt itself does not use config. 

will close here since it's better to discuss questions on stackoverflow.
