### ISSUE TITLE
Should one use Config for "run-time" values?

### ISSUE THREAD

**Issue by hayohayo** [typesafehub/config#354]
Hello,

Rather than reporting an issue, I just want to ask for a clarification/advice. Can/should I use `Config` for run-time values - something that is specific to this particular instance of application or this user? Like passing user ID, email, device ID, advertising ID, etc. Assuming that these are evaluated in run-time at some point and may not be available, when "built-time" `Config` is loaded. I somehow feel that these are different...

Is it better to merge build and run-time configs, when initializing components?
```
Foo myFoo = new Foo(runtimeConfig.withFallback(config));
```
Keeping them separately? 
```
Foo myFoo = new Foo(config, runtimeConfig);
```
Or is it just plain wrong for whatever reason to use `Config` for run-time properties?
```
Foo myFoo = new Foo(config, userId, email, advertisingId);
```

Thanks!

**Comment by havocp** [comment]
I would say Config simply loads a file, it's up to you whether you create the file at build time or deploy time or runtime or all three. One thing the library doesn't support that well is changing config after the app starts up, though, if that matters. It's usually used to load once at startup.

**Comment by jec** [comment]
I'm considering using Config for runtime/dynamic application configuration as well. I currently have a dynamic config setup where remote apps periodically poll a central server for their configs. Currently these are Ruby apps pulling down YAML, but I'm replacing one of the apps with a new version written in Scala. I could arrange to have the config server emit HOCON instead of YAML depending on the URL requested. The receiving app could then use ConfigFactory.parseString() with the HOCON it receives. Does this seem like a reasonable use of Config?

**Comment by havocp** [comment]
It's fine to use Config dynamically you just have to realize you're getting an immutable config object so change notification will be your responsibility and involves getting a new Config rather than changing an existing one.
