### ISSUE TITLE
Release roadmap is missing

### ISSUE THREAD

**Issue by pshirshov** [typesafehub/config#420]
Hi guys,

I'm pretty curious when are you going to make next release? 
A lot of time passed since last one. And a lot of fixes have been made.

**Comment by havocp** [comment]
The release instructions are in CONTRIBUTING.md ; I think the main work might be to dig through commits to create a NEWS.md entry, and to figure out the right version number.

There's definitely a maintenance shortage on the library, I was keeping up with it at Lightbend but now that I left it's fallen through the cracks. I've been trying to be responsive to discussions but actually sitting down for hours to work on code is hard for me at the moment. My JVM dev environment isn't even set up.

On the plus side I think the library pretty much works and all the fixes are nice-to-have rather than showstoppers, which is a double-edged sword since nobody's hair is on fire to allocate time to it :-)

Due to the lack of dependencies, and the test coverage, there's been amazingly little bit rot. It works and keeps working.

Other than a release there's a backlog of small issues that really could use patches, and some feature requests that genuinely would be nice.

Anyway that's the status...

**Comment by havocp** [comment]
I updated NEWS.md just now; a few minor features and bugfixes in there, nothing earth-shaking. @patriknw / @2m / @viktorklang do you have any thoughts on the version number to use for a new release? It should be ABI-compatible and low-risk, but there are a few feature additions as noted in NEWS.md.

I can type "sbt publish" but I don't have time to go through issues and fix anything that isn't already fixed.

**Comment by 2m** [comment]
I think we should keep with the versioning practice we had so far. Change from 1.2 to 1.3 was big as it started requiring Java 8 and did API changes. So bumping to 1.4 might set wrong expectations. Lets release 1.3.1.

**Comment by havocp** [comment]
I released 1.3.1 now; I didn't go through open issues or do any work, just shipped master as it was, since otherwise we'd be waiting a long time :-)

Please test. If something is wrong I can release 1.3.2.

Thanks

**Comment by pshirshov** [comment]
Thank you so much!
