### ISSUE TITLE
On the goals of HOCON and other similar data representation formats

### ISSUE THREAD

**Issue by CrudKing** [typesafehub/config#439]
Hi Folks,

Would it be correct to say that ultimately the goal of data representation formats such as HOCON et al (JSON,Java Properties, XML (to some extent), YAML, CSON...etc) is to represent object graphs? ie sets of name/value pairs with support for composition (ie nesting) and sequences (ie arrays).

The syntactic goal then of each format is to balance machine readability (ie parsing) with human readability.

Am I off base on this? 

I am asking because it seems a better approach for all of this is to just develop a way to construct object graphs directly without relying on any particular format representation.

I have developed a JVM based platform that does precisely this, I have a write up on it here: http://blog.crudzilla.com/2016/10/managing-configurations-with-object.html

You can login to the demo referenced in the link above with developer/developer.

I would like to hear feedback from folks and happy to answer any questions.

-Edmond

**Comment by havocp** [comment]
For background see https://blog.ometer.com/2011/12/09/configuring-the-typesafe-stack/

In general the way Typesafe Config apps work it should be straightforward to pull in a JSON-like data structure from anywhere. It isn't required to use the HOCON format.

This library doesn't contain abstractions for "where config comes from" for the most part though (if you wanted to load config from a service or a db, that would be done outside of this lib). We do let you specify a URL or file to load from, so if a service could provide a config as JSON, then it could go to typesafe config.

Closing this issue because it isn't clear to me what further action would result in closing it, but feel free to continue to discuss here on or gitter.
