### ISSUE TITLE
Config parser

### ISSUE THREAD

**Issue by Vadi** [typesafehub/config#443]
I was surprised to see there were no grammar files for parsing the Configuration file. Wouldn't help to have a parser/lexer so that we can easily build editors and tools to support Config syntax. Any explanation would be great.

Thx.

**Comment by havocp** [comment]
The library has a hand-coded parser because I think it produces a better result (such as better error messages). But there are enough unit tests that someone could confidently swap in a generated parser knowing nothing was broken (if all tests still pass).

Nothing prevents an editor or other tool from using a generated parser; some may already in fact, not sure.

**Comment by Vadi** [comment]
Great. That means we can develop one (may be in Antlr) and run unit tests against it. Thanks for the info.

**Comment by havocp** [comment]
yeah. I mean, the unit tests aren't set up
as an implementation-independent TCK kind of thing, but maybe one could be based on them.
