### ISSUE TITLE
Quick documentation on using CONF file external to a JAR

### ISSUE THREAD

**Issue by igozali** [typesafehub/config#84]
Hi guys,

I've been scratching my head and trying to find documentation on how to do this. 

Basically, I have a standalone, executable JAR which contains a `reference.conf` in its `src/main/resource` folder. 

I want to be able to pass in an `application.conf` that is external to this JAR and  overrides the `resource.conf`. 

Here's some examples of how I think I should be doing it:

```
$ ls
standalone.jar    application.conf

$ java -cp standalone.jar com.standalone.Main
Option 1. Running com.standalone.Main with reference.conf included inside the JAR.

$ java -cp standalone.jar:application.conf com.standalone.Main
Option 2. Running com.standalone.Main with application.conf inside the classpath

$ java -cp standalone.jar com.standalone.Main application.conf
Option 3. Running com.standalone.Main with application.conf passed in through command-line arguments
```

It would be great if you can help me with this, or provide documentation on how to do this, since this seems like something a lot of people might want to do? 

Thanks in advance!

**Comment by gratner** [comment]
@havocp - The above doesn't work for me. I have an app packaged with sbt-assembly. Is there a way to still pass in an external config?

**Comment by havocp** [comment]
Should be the same. Maybe ask on stackoverflow, that's a better place for support since it's easier for others to help and easier for future searches to find. I would include though what you are trying exactly, and exactly what goes wrong. The usual problem with sbt-assembly is that filename collisions cause some of the .conf files to be lost from the combined jar. There should be nothing different about an sbt-assembly app unless that has happened.

**Comment by gratner** [comment]
Thanks, posted this
http://stackoverflow.com/questions/31276537/command-line-arguments-not-working-for-sbt-assembly-jars

**Comment by havocp** [comment]
I don't think there's a feature for loading a directory; you'd have to do something like make a .conf file that includes everything in the directory
